### ISSUE TITLE
tesla-auth打包出错

### ISSUE THREAD

**Issue by xdering** [ke-finance/tesla#2]
[ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find com.bkjk.platform.summerframework:summerframework-dependencies:pom:2.0.0.RELEASE in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced @ line 50, column 25

**Comment by linking12** [comment]
请先构建summerframewoek，构建流程看下readme
